name: blekker
description: Lead sheet repository and planner
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  appwrite: ^12.0.3
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^7.0.0
  fpdart: ^1.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  mockito: ^5.4.4
  path_provider: ^2.1.3
  pdfrx: ^1.0.65
  shared_preferences: ^2.2.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
