// Copyright 2024 Sifterstudios

// Mocks generated by Mockito 5.4.4 from annotations
// in blekker/test/features/auth/data/datasources/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:appwrite/appwrite.dart' as _i5;
import 'package:appwrite/enums.dart' as _i7;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:appwrite/src/enums.dart' as _i10;
import 'package:appwrite/src/response.dart' as _i4;
import 'package:appwrite/src/upload_progress.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdentityList_2 extends _i1.SmartFake implements _i3.IdentityList {
  _FakeIdentityList_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJwt_3 extends _i1.SmartFake implements _i3.Jwt {
  _FakeJwt_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogList_4 extends _i1.SmartFake implements _i3.LogList {
  _FakeLogList_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaType_5 extends _i1.SmartFake implements _i3.MfaType {
  _FakeMfaType_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaChallenge_6 extends _i1.SmartFake implements _i3.MfaChallenge {
  _FakeMfaChallenge_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaFactors_7 extends _i1.SmartFake implements _i3.MfaFactors {
  _FakeMfaFactors_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaRecoveryCodes_8 extends _i1.SmartFake
    implements _i3.MfaRecoveryCodes {
  _FakeMfaRecoveryCodes_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferences_9 extends _i1.SmartFake implements _i3.Preferences {
  _FakePreferences_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToken_10 extends _i1.SmartFake implements _i3.Token {
  _FakeToken_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionList_11 extends _i1.SmartFake implements _i3.SessionList {
  _FakeSessionList_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_12 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTarget_13 extends _i1.SmartFake implements _i3.Target {
  _FakeTarget_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_14<T> extends _i1.SmartFake implements _i4.Response<T> {
  _FakeResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Account].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccount extends _i1.Mock implements _i5.Account {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i6.Future<_i3.User> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> create({
    required String? userId,
    required String? email,
    required String? password,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #userId: userId,
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #create,
            [],
            {
              #userId: userId,
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #create,
            [],
            {
              #userId: userId,
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> updateEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.IdentityList> listIdentities({List<String>? queries}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listIdentities,
          [],
          {#queries: queries},
        ),
        returnValue: _i6.Future<_i3.IdentityList>.value(_FakeIdentityList_2(
          this,
          Invocation.method(
            #listIdentities,
            [],
            {#queries: queries},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.IdentityList>.value(_FakeIdentityList_2(
          this,
          Invocation.method(
            #listIdentities,
            [],
            {#queries: queries},
          ),
        )),
      ) as _i6.Future<_i3.IdentityList>);

  @override
  _i6.Future<dynamic> deleteIdentity({required String? identityId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIdentity,
          [],
          {#identityId: identityId},
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Jwt> createJWT() => (super.noSuchMethod(
        Invocation.method(
          #createJWT,
          [],
        ),
        returnValue: _i6.Future<_i3.Jwt>.value(_FakeJwt_3(
          this,
          Invocation.method(
            #createJWT,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Jwt>.value(_FakeJwt_3(
          this,
          Invocation.method(
            #createJWT,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Jwt>);

  @override
  _i6.Future<_i3.LogList> listLogs({List<String>? queries}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLogs,
          [],
          {#queries: queries},
        ),
        returnValue: _i6.Future<_i3.LogList>.value(_FakeLogList_4(
          this,
          Invocation.method(
            #listLogs,
            [],
            {#queries: queries},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.LogList>.value(_FakeLogList_4(
          this,
          Invocation.method(
            #listLogs,
            [],
            {#queries: queries},
          ),
        )),
      ) as _i6.Future<_i3.LogList>);

  @override
  _i6.Future<_i3.User> updateMFA({required bool? mfa}) => (super.noSuchMethod(
        Invocation.method(
          #updateMFA,
          [],
          {#mfa: mfa},
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateMFA,
            [],
            {#mfa: mfa},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateMFA,
            [],
            {#mfa: mfa},
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.MfaType> createMfaAuthenticator(
          {required _i7.AuthenticatorType? type}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaAuthenticator,
          [],
          {#type: type},
        ),
        returnValue: _i6.Future<_i3.MfaType>.value(_FakeMfaType_5(
          this,
          Invocation.method(
            #createMfaAuthenticator,
            [],
            {#type: type},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.MfaType>.value(_FakeMfaType_5(
          this,
          Invocation.method(
            #createMfaAuthenticator,
            [],
            {#type: type},
          ),
        )),
      ) as _i6.Future<_i3.MfaType>);

  @override
  _i6.Future<_i3.User> updateMfaAuthenticator({
    required _i7.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaAuthenticator,
          [],
          {
            #type: type,
            #otp: otp,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> deleteMfaAuthenticator({
    required _i7.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMfaAuthenticator,
          [],
          {
            #type: type,
            #otp: otp,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #deleteMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #deleteMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.MfaChallenge> createMfaChallenge(
          {required _i7.AuthenticationFactor? factor}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaChallenge,
          [],
          {#factor: factor},
        ),
        returnValue: _i6.Future<_i3.MfaChallenge>.value(_FakeMfaChallenge_6(
          this,
          Invocation.method(
            #createMfaChallenge,
            [],
            {#factor: factor},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaChallenge>.value(_FakeMfaChallenge_6(
          this,
          Invocation.method(
            #createMfaChallenge,
            [],
            {#factor: factor},
          ),
        )),
      ) as _i6.Future<_i3.MfaChallenge>);

  @override
  _i6.Future<dynamic> updateMfaChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaChallenge,
          [],
          {
            #challengeId: challengeId,
            #otp: otp,
          },
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.MfaFactors> listMfaFactors() => (super.noSuchMethod(
        Invocation.method(
          #listMfaFactors,
          [],
        ),
        returnValue: _i6.Future<_i3.MfaFactors>.value(_FakeMfaFactors_7(
          this,
          Invocation.method(
            #listMfaFactors,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaFactors>.value(_FakeMfaFactors_7(
          this,
          Invocation.method(
            #listMfaFactors,
            [],
          ),
        )),
      ) as _i6.Future<_i3.MfaFactors>);

  @override
  _i6.Future<_i3.MfaRecoveryCodes> getMfaRecoveryCodes() => (super.noSuchMethod(
        Invocation.method(
          #getMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #getMfaRecoveryCodes,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #getMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i6.Future<_i3.MfaRecoveryCodes>);

  @override
  _i6.Future<_i3.MfaRecoveryCodes> createMfaRecoveryCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #createMfaRecoveryCodes,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #createMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i6.Future<_i3.MfaRecoveryCodes>);

  @override
  _i6.Future<_i3.MfaRecoveryCodes> updateMfaRecoveryCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #updateMfaRecoveryCodes,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_8(
          this,
          Invocation.method(
            #updateMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i6.Future<_i3.MfaRecoveryCodes>);

  @override
  _i6.Future<_i3.User> updateName({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [],
          {#name: name},
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateName,
            [],
            {#name: name},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateName,
            [],
            {#name: name},
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> updatePassword({
    required String? password,
    String? oldPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #password: password,
            #oldPassword: oldPassword,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #password: password,
              #oldPassword: oldPassword,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #password: password,
              #oldPassword: oldPassword,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.User> updatePhone({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhone,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePhone,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePhone,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.Preferences> getPrefs() => (super.noSuchMethod(
        Invocation.method(
          #getPrefs,
          [],
        ),
        returnValue: _i6.Future<_i3.Preferences>.value(_FakePreferences_9(
          this,
          Invocation.method(
            #getPrefs,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Preferences>.value(_FakePreferences_9(
          this,
          Invocation.method(
            #getPrefs,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Preferences>);

  @override
  _i6.Future<_i3.User> updatePrefs({required Map<dynamic, dynamic>? prefs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrefs,
          [],
          {#prefs: prefs},
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePrefs,
            [],
            {#prefs: prefs},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updatePrefs,
            [],
            {#prefs: prefs},
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.Token> createRecovery({
    required String? email,
    required String? url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecovery,
          [],
          {
            #email: email,
            #url: url,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createRecovery,
            [],
            {
              #email: email,
              #url: url,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createRecovery,
            [],
            {
              #email: email,
              #url: url,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> updateRecovery({
    required String? userId,
    required String? secret,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecovery,
          [],
          {
            #userId: userId,
            #secret: secret,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updateRecovery,
            [],
            {
              #userId: userId,
              #secret: secret,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updateRecovery,
            [],
            {
              #userId: userId,
              #secret: secret,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.SessionList> listSessions() => (super.noSuchMethod(
        Invocation.method(
          #listSessions,
          [],
        ),
        returnValue: _i6.Future<_i3.SessionList>.value(_FakeSessionList_11(
          this,
          Invocation.method(
            #listSessions,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.SessionList>.value(_FakeSessionList_11(
          this,
          Invocation.method(
            #listSessions,
            [],
          ),
        )),
      ) as _i6.Future<_i3.SessionList>);

  @override
  _i6.Future<dynamic> deleteSessions() => (super.noSuchMethod(
        Invocation.method(
          #deleteSessions,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Session> createAnonymousSession() => (super.noSuchMethod(
        Invocation.method(
          #createAnonymousSession,
          [],
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createAnonymousSession,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createAnonymousSession,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> createEmailPasswordSession({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmailPasswordSession,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createEmailPasswordSession,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createEmailPasswordSession,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> updateMagicURLSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMagicURLSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updateMagicURLSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updateMagicURLSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<dynamic> createOAuth2Session({
    required _i7.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOAuth2Session,
          [],
          {
            #provider: provider,
            #success: success,
            #failure: failure,
            #scopes: scopes,
          },
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Session> updatePhoneSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updatePhoneSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updatePhoneSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> createSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #createSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> getSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #getSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #getSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<_i3.Session> updateSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updateSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Session>.value(_FakeSession_12(
          this,
          Invocation.method(
            #updateSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
      ) as _i6.Future<_i3.Session>);

  @override
  _i6.Future<dynamic> deleteSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.User> updateStatus() => (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [],
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateStatus,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #updateStatus,
            [],
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<_i3.Target> createPushTarget({
    required String? targetId,
    required String? identifier,
    String? providerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPushTarget,
          [],
          {
            #targetId: targetId,
            #identifier: identifier,
            #providerId: providerId,
          },
        ),
        returnValue: _i6.Future<_i3.Target>.value(_FakeTarget_13(
          this,
          Invocation.method(
            #createPushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
              #providerId: providerId,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Target>.value(_FakeTarget_13(
          this,
          Invocation.method(
            #createPushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
              #providerId: providerId,
            },
          ),
        )),
      ) as _i6.Future<_i3.Target>);

  @override
  _i6.Future<_i3.Target> updatePushTarget({
    required String? targetId,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePushTarget,
          [],
          {
            #targetId: targetId,
            #identifier: identifier,
          },
        ),
        returnValue: _i6.Future<_i3.Target>.value(_FakeTarget_13(
          this,
          Invocation.method(
            #updatePushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Target>.value(_FakeTarget_13(
          this,
          Invocation.method(
            #updatePushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
            },
          ),
        )),
      ) as _i6.Future<_i3.Target>);

  @override
  _i6.Future<dynamic> deletePushTarget({required String? targetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePushTarget,
          [],
          {#targetId: targetId},
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Token> createEmailToken({
    required String? userId,
    required String? email,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmailToken,
          [],
          {
            #userId: userId,
            #email: email,
            #phrase: phrase,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createEmailToken,
            [],
            {
              #userId: userId,
              #email: email,
              #phrase: phrase,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createEmailToken,
            [],
            {
              #userId: userId,
              #email: email,
              #phrase: phrase,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> createMagicURLToken({
    required String? userId,
    required String? email,
    String? url,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMagicURLToken,
          [],
          {
            #userId: userId,
            #email: email,
            #url: url,
            #phrase: phrase,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createMagicURLToken,
            [],
            {
              #userId: userId,
              #email: email,
              #url: url,
              #phrase: phrase,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createMagicURLToken,
            [],
            {
              #userId: userId,
              #email: email,
              #url: url,
              #phrase: phrase,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<dynamic> createOAuth2Token({
    required _i7.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOAuth2Token,
          [],
          {
            #provider: provider,
            #success: success,
            #failure: failure,
            #scopes: scopes,
          },
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Token> createPhoneToken({
    required String? userId,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPhoneToken,
          [],
          {
            #userId: userId,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createPhoneToken,
            [],
            {
              #userId: userId,
              #phone: phone,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createPhoneToken,
            [],
            {
              #userId: userId,
              #phone: phone,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> createVerification({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVerification,
          [],
          {#url: url},
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createVerification,
            [],
            {#url: url},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createVerification,
            [],
            {#url: url},
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> updateVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVerification,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updateVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updateVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> createPhoneVerification() => (super.noSuchMethod(
        Invocation.method(
          #createPhoneVerification,
          [],
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createPhoneVerification,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #createPhoneVerification,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Token>);

  @override
  _i6.Future<_i3.Token> updatePhoneVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneVerification,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updatePhoneVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Token>.value(_FakeToken_10(
          this,
          Invocation.method(
            #updatePhoneVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i6.Future<_i3.Token>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  @override
  Map<String, String> get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  set config(Map<String, String>? _config) => super.noSuchMethod(
        Invocation.setter(
          #config,
          _config,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get endPoint => (super.noSuchMethod(
        Invocation.getter(#endPoint),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#endPoint),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#endPoint),
        ),
      ) as String);

  @override
  _i6.Future<dynamic> webAuth(
    Uri? url, {
    String? callbackUrlScheme,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #webAuth,
          [url],
          {#callbackUrlScheme: callbackUrlScheme},
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i4.Response<dynamic>> chunkedUpload({
    required String? path,
    required Map<String, dynamic>? params,
    required String? paramName,
    required String? idParamName,
    required Map<String, String>? headers,
    dynamic Function(_i9.UploadProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chunkedUpload,
          [],
          {
            #path: path,
            #params: params,
            #paramName: paramName,
            #idParamName: idParamName,
            #headers: headers,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i6.Future<_i4.Response<dynamic>>.value(_FakeResponse_14<dynamic>(
          this,
          Invocation.method(
            #chunkedUpload,
            [],
            {
              #path: path,
              #params: params,
              #paramName: paramName,
              #idParamName: idParamName,
              #headers: headers,
              #onProgress: onProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.Response<dynamic>>.value(_FakeResponse_14<dynamic>(
          this,
          Invocation.method(
            #chunkedUpload,
            [],
            {
              #path: path,
              #params: params,
              #paramName: paramName,
              #idParamName: idParamName,
              #headers: headers,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<dynamic>>);

  @override
  _i2.Client setSelfSigned({bool? status = true}) => (super.noSuchMethod(
        Invocation.method(
          #setSelfSigned,
          [],
          {#status: status},
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setSelfSigned,
            [],
            {#status: status},
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setSelfSigned,
            [],
            {#status: status},
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setEndpoint(String? endPoint) => (super.noSuchMethod(
        Invocation.method(
          #setEndpoint,
          [endPoint],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setEndpoint,
            [endPoint],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setEndpoint,
            [endPoint],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setEndPointRealtime(String? endPoint) => (super.noSuchMethod(
        Invocation.method(
          #setEndPointRealtime,
          [endPoint],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setEndPointRealtime,
            [endPoint],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setEndPointRealtime,
            [endPoint],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setProject(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setProject,
          [value],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setProject,
            [value],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setProject,
            [value],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setJWT(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setJWT,
          [value],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setJWT,
            [value],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setJWT,
            [value],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setLocale(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [value],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setLocale,
            [value],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setLocale,
            [value],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client setSession(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [value],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #setSession,
            [value],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #setSession,
            [value],
          ),
        ),
      ) as _i2.Client);

  @override
  _i2.Client addHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHeader,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeClient_0(
          this,
          Invocation.method(
            #addHeader,
            [
              key,
              value,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.method(
            #addHeader,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i2.Client);

  @override
  _i6.Future<_i4.Response<dynamic>> call(
    _i10.HttpMethod? method, {
    String? path = r'',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? params = const {},
    _i10.ResponseType? responseType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [method],
          {
            #path: path,
            #headers: headers,
            #params: params,
            #responseType: responseType,
          },
        ),
        returnValue:
            _i6.Future<_i4.Response<dynamic>>.value(_FakeResponse_14<dynamic>(
          this,
          Invocation.method(
            #call,
            [method],
            {
              #path: path,
              #headers: headers,
              #params: params,
              #responseType: responseType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.Response<dynamic>>.value(_FakeResponse_14<dynamic>(
          this,
          Invocation.method(
            #call,
            [method],
            {
              #path: path,
              #headers: headers,
              #params: params,
              #responseType: responseType,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response<dynamic>>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  String get $id => (super.noSuchMethod(
        Invocation.getter(#$id),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
      ) as String);

  @override
  String get $createdAt => (super.noSuchMethod(
        Invocation.getter(#$createdAt),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
      ) as String);

  @override
  String get $updatedAt => (super.noSuchMethod(
        Invocation.getter(#$updatedAt),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$updatedAt),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#$updatedAt),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get registration => (super.noSuchMethod(
        Invocation.getter(#registration),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#registration),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#registration),
        ),
      ) as String);

  @override
  bool get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<dynamic> get labels => (super.noSuchMethod(
        Invocation.getter(#labels),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  String get passwordUpdate => (super.noSuchMethod(
        Invocation.getter(#passwordUpdate),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#passwordUpdate),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#passwordUpdate),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
      ) as String);

  @override
  bool get emailVerification => (super.noSuchMethod(
        Invocation.getter(#emailVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get phoneVerification => (super.noSuchMethod(
        Invocation.getter(#phoneVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Preferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakePreferences_9(
          this,
          Invocation.getter(#prefs),
        ),
        returnValueForMissingStub: _FakePreferences_9(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i3.Preferences);

  @override
  List<_i3.Target> get targets => (super.noSuchMethod(
        Invocation.getter(#targets),
        returnValue: <_i3.Target>[],
        returnValueForMissingStub: <_i3.Target>[],
      ) as List<_i3.Target>);

  @override
  String get accessedAt => (super.noSuchMethod(
        Invocation.getter(#accessedAt),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#accessedAt),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#accessedAt),
        ),
      ) as String);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
