// Copyright 2024 Sifterstudios

// Mocks generated by Mockito 5.4.4 from annotations
// in blekker/test/features/auth/data/repository/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:appwrite/models.dart' as _i2;
import 'package:blekker/app/utils/equatable/equatable_date_time.dart' as _i3;
import 'package:blekker/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:blekker/features/auth/domain/entities/session_entity.dart'
    as _i8;
import 'package:blekker/features/auth/domain/entities/user_entity.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_1 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferences_2 extends _i1.SmartFake implements _i2.Preferences {
  _FakePreferences_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEquatableDateTime_3 extends _i1.SmartFake
    implements _i3.EquatableDateTime {
  _FakeEquatableDateTime_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_5 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  @override
  _i5.Future<_i2.User> signupWithEmailAndPassword({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signupWithEmailAndPassword,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #signupWithEmailAndPassword,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #signupWithEmailAndPassword,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.Session> loginWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.Session>.value(_FakeSession_1(
          this,
          Invocation.method(
            #loginWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.Session>.value(_FakeSession_1(
          this,
          Invocation.method(
            #loginWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.Session>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  @override
  String get $id => (super.noSuchMethod(
        Invocation.getter(#$id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
      ) as String);

  @override
  String get $createdAt => (super.noSuchMethod(
        Invocation.getter(#$createdAt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
      ) as String);

  @override
  String get $updatedAt => (super.noSuchMethod(
        Invocation.getter(#$updatedAt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$updatedAt),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$updatedAt),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get registration => (super.noSuchMethod(
        Invocation.getter(#registration),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#registration),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#registration),
        ),
      ) as String);

  @override
  bool get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<dynamic> get labels => (super.noSuchMethod(
        Invocation.getter(#labels),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  String get passwordUpdate => (super.noSuchMethod(
        Invocation.getter(#passwordUpdate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#passwordUpdate),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#passwordUpdate),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
      ) as String);

  @override
  bool get emailVerification => (super.noSuchMethod(
        Invocation.getter(#emailVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get phoneVerification => (super.noSuchMethod(
        Invocation.getter(#phoneVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Preferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakePreferences_2(
          this,
          Invocation.getter(#prefs),
        ),
        returnValueForMissingStub: _FakePreferences_2(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i2.Preferences);

  @override
  List<_i2.Target> get targets => (super.noSuchMethod(
        Invocation.getter(#targets),
        returnValue: <_i2.Target>[],
        returnValueForMissingStub: <_i2.Target>[],
      ) as List<_i2.Target>);

  @override
  String get accessedAt => (super.noSuchMethod(
        Invocation.getter(#accessedAt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#accessedAt),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#accessedAt),
        ),
      ) as String);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [UserEntity].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockUserEntity extends _i1.Mock implements _i7.UserEntity {
  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i3.EquatableDateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#createdAt),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as _i3.EquatableDateTime);

  @override
  _i3.EquatableDateTime get updatedAt => (super.noSuchMethod(
        Invocation.getter(#updatedAt),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#updatedAt),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#updatedAt),
        ),
      ) as _i3.EquatableDateTime);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  _i3.EquatableDateTime get registration => (super.noSuchMethod(
        Invocation.getter(#registration),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#registration),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#registration),
        ),
      ) as _i3.EquatableDateTime);

  @override
  bool get activeStatus => (super.noSuchMethod(
        Invocation.getter(#activeStatus),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<dynamic> get labels => (super.noSuchMethod(
        Invocation.getter(#labels),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i3.EquatableDateTime get passwordUpdate => (super.noSuchMethod(
        Invocation.getter(#passwordUpdate),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#passwordUpdate),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#passwordUpdate),
        ),
      ) as _i3.EquatableDateTime);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
      ) as String);

  @override
  bool get emailVerification => (super.noSuchMethod(
        Invocation.getter(#emailVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get phoneVerification => (super.noSuchMethod(
        Invocation.getter(#phoneVerification),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.EquatableDateTime get accessedAt => (super.noSuchMethod(
        Invocation.getter(#accessedAt),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#accessedAt),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#accessedAt),
        ),
      ) as _i3.EquatableDateTime);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
        returnValueForMissingStub: <Object?>[],
      ) as List<Object?>);

  @override
  _i2.User toUser() => (super.noSuchMethod(
        Invocation.method(
          #toUser,
          [],
        ),
        returnValue: _FakeUser_0(
          this,
          Invocation.method(
            #toUser,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.method(
            #toUser,
            [],
          ),
        ),
      ) as _i2.User);
}

/// A class which mocks [DateTime].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTime extends _i1.Mock implements DateTime {
  @override
  bool get isUtc => (super.noSuchMethod(
        Invocation.getter(#isUtc),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get millisecondsSinceEpoch => (super.noSuchMethod(
        Invocation.getter(#millisecondsSinceEpoch),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get microsecondsSinceEpoch => (super.noSuchMethod(
        Invocation.getter(#microsecondsSinceEpoch),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get timeZoneName => (super.noSuchMethod(
        Invocation.getter(#timeZoneName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#timeZoneName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#timeZoneName),
        ),
      ) as String);

  @override
  Duration get timeZoneOffset => (super.noSuchMethod(
        Invocation.getter(#timeZoneOffset),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#timeZoneOffset),
        ),
        returnValueForMissingStub: _FakeDuration_4(
          this,
          Invocation.getter(#timeZoneOffset),
        ),
      ) as Duration);

  @override
  int get year => (super.noSuchMethod(
        Invocation.getter(#year),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get month => (super.noSuchMethod(
        Invocation.getter(#month),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get day => (super.noSuchMethod(
        Invocation.getter(#day),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get hour => (super.noSuchMethod(
        Invocation.getter(#hour),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get minute => (super.noSuchMethod(
        Invocation.getter(#minute),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get second => (super.noSuchMethod(
        Invocation.getter(#second),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get millisecond => (super.noSuchMethod(
        Invocation.getter(#millisecond),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get microsecond => (super.noSuchMethod(
        Invocation.getter(#microsecond),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get weekday => (super.noSuchMethod(
        Invocation.getter(#weekday),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isBefore(DateTime? other) => (super.noSuchMethod(
        Invocation.method(
          #isBefore,
          [other],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isAfter(DateTime? other) => (super.noSuchMethod(
        Invocation.method(
          #isAfter,
          [other],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isAtSameMomentAs(DateTime? other) => (super.noSuchMethod(
        Invocation.method(
          #isAtSameMomentAs,
          [other],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int compareTo(DateTime? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  DateTime toLocal() => (super.noSuchMethod(
        Invocation.method(
          #toLocal,
          [],
        ),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.method(
            #toLocal,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_5(
          this,
          Invocation.method(
            #toLocal,
            [],
          ),
        ),
      ) as DateTime);

  @override
  DateTime toUtc() => (super.noSuchMethod(
        Invocation.method(
          #toUtc,
          [],
        ),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.method(
            #toUtc,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_5(
          this,
          Invocation.method(
            #toUtc,
            [],
          ),
        ),
      ) as DateTime);

  @override
  String toIso8601String() => (super.noSuchMethod(
        Invocation.method(
          #toIso8601String,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toIso8601String,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toIso8601String,
            [],
          ),
        ),
      ) as String);

  @override
  DateTime add(Duration? duration) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [duration],
        ),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.method(
            #add,
            [duration],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_5(
          this,
          Invocation.method(
            #add,
            [duration],
          ),
        ),
      ) as DateTime);

  @override
  DateTime subtract(Duration? duration) => (super.noSuchMethod(
        Invocation.method(
          #subtract,
          [duration],
        ),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.method(
            #subtract,
            [duration],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_5(
          this,
          Invocation.method(
            #subtract,
            [duration],
          ),
        ),
      ) as DateTime);

  @override
  Duration difference(DateTime? other) => (super.noSuchMethod(
        Invocation.method(
          #difference,
          [other],
        ),
        returnValue: _FakeDuration_4(
          this,
          Invocation.method(
            #difference,
            [other],
          ),
        ),
        returnValueForMissingStub: _FakeDuration_4(
          this,
          Invocation.method(
            #difference,
            [other],
          ),
        ),
      ) as Duration);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i2.Session {
  @override
  String get $id => (super.noSuchMethod(
        Invocation.getter(#$id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
      ) as String);

  @override
  String get $createdAt => (super.noSuchMethod(
        Invocation.getter(#$createdAt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
      ) as String);

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  String get expire => (super.noSuchMethod(
        Invocation.getter(#expire),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#expire),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#expire),
        ),
      ) as String);

  @override
  String get provider => (super.noSuchMethod(
        Invocation.getter(#provider),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#provider),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#provider),
        ),
      ) as String);

  @override
  String get providerUid => (super.noSuchMethod(
        Invocation.getter(#providerUid),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerUid),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerUid),
        ),
      ) as String);

  @override
  String get providerAccessToken => (super.noSuchMethod(
        Invocation.getter(#providerAccessToken),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessToken),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessToken),
        ),
      ) as String);

  @override
  String get providerAccessTokenExpiry => (super.noSuchMethod(
        Invocation.getter(#providerAccessTokenExpiry),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessTokenExpiry),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessTokenExpiry),
        ),
      ) as String);

  @override
  String get providerRefreshToken => (super.noSuchMethod(
        Invocation.getter(#providerRefreshToken),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerRefreshToken),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerRefreshToken),
        ),
      ) as String);

  @override
  String get ip => (super.noSuchMethod(
        Invocation.getter(#ip),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ip),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ip),
        ),
      ) as String);

  @override
  String get osCode => (super.noSuchMethod(
        Invocation.getter(#osCode),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osCode),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osCode),
        ),
      ) as String);

  @override
  String get osName => (super.noSuchMethod(
        Invocation.getter(#osName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osName),
        ),
      ) as String);

  @override
  String get osVersion => (super.noSuchMethod(
        Invocation.getter(#osVersion),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osVersion),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#osVersion),
        ),
      ) as String);

  @override
  String get clientType => (super.noSuchMethod(
        Invocation.getter(#clientType),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientType),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientType),
        ),
      ) as String);

  @override
  String get clientCode => (super.noSuchMethod(
        Invocation.getter(#clientCode),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientCode),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientCode),
        ),
      ) as String);

  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  String get clientVersion => (super.noSuchMethod(
        Invocation.getter(#clientVersion),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientVersion),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientVersion),
        ),
      ) as String);

  @override
  String get clientEngine => (super.noSuchMethod(
        Invocation.getter(#clientEngine),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientEngine),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientEngine),
        ),
      ) as String);

  @override
  String get clientEngineVersion => (super.noSuchMethod(
        Invocation.getter(#clientEngineVersion),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientEngineVersion),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientEngineVersion),
        ),
      ) as String);

  @override
  String get deviceName => (super.noSuchMethod(
        Invocation.getter(#deviceName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceName),
        ),
      ) as String);

  @override
  String get deviceBrand => (super.noSuchMethod(
        Invocation.getter(#deviceBrand),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceBrand),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceBrand),
        ),
      ) as String);

  @override
  String get deviceModel => (super.noSuchMethod(
        Invocation.getter(#deviceModel),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceModel),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#deviceModel),
        ),
      ) as String);

  @override
  String get countryCode => (super.noSuchMethod(
        Invocation.getter(#countryCode),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#countryCode),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#countryCode),
        ),
      ) as String);

  @override
  String get countryName => (super.noSuchMethod(
        Invocation.getter(#countryName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#countryName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#countryName),
        ),
      ) as String);

  @override
  bool get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<dynamic> get factors => (super.noSuchMethod(
        Invocation.getter(#factors),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);

  @override
  String get secret => (super.noSuchMethod(
        Invocation.getter(#secret),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#secret),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#secret),
        ),
      ) as String);

  @override
  String get mfaUpdatedAt => (super.noSuchMethod(
        Invocation.getter(#mfaUpdatedAt),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#mfaUpdatedAt),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#mfaUpdatedAt),
        ),
      ) as String);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [SessionEntity].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockSessionEntity extends _i1.Mock implements _i8.SessionEntity {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i3.EquatableDateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#createdAt),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as _i3.EquatableDateTime);

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  _i3.EquatableDateTime get expire => (super.noSuchMethod(
        Invocation.getter(#expire),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#expire),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#expire),
        ),
      ) as _i3.EquatableDateTime);

  @override
  String get provider => (super.noSuchMethod(
        Invocation.getter(#provider),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#provider),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#provider),
        ),
      ) as String);

  @override
  String get providerUid => (super.noSuchMethod(
        Invocation.getter(#providerUid),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerUid),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerUid),
        ),
      ) as String);

  @override
  String get providerAccessToken => (super.noSuchMethod(
        Invocation.getter(#providerAccessToken),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessToken),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerAccessToken),
        ),
      ) as String);

  @override
  _i3.EquatableDateTime get providerAccessTokenExpiry => (super.noSuchMethod(
        Invocation.getter(#providerAccessTokenExpiry),
        returnValue: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#providerAccessTokenExpiry),
        ),
        returnValueForMissingStub: _FakeEquatableDateTime_3(
          this,
          Invocation.getter(#providerAccessTokenExpiry),
        ),
      ) as _i3.EquatableDateTime);

  @override
  String get providerRefreshToken => (super.noSuchMethod(
        Invocation.getter(#providerRefreshToken),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerRefreshToken),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#providerRefreshToken),
        ),
      ) as String);

  @override
  String get ip => (super.noSuchMethod(
        Invocation.getter(#ip),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ip),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#ip),
        ),
      ) as String);

  @override
  bool get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
        returnValueForMissingStub: <Object?>[],
      ) as List<Object?>);
}
